export interface Country {
    name: string;
    code: string; // ISO 3166-1 alpha-2 (lowercase)
}

/** Tous les pays reconnus, triés alphabétiquement par nom français */
export const COUNTRIES: Country[] = [
    { name: "Afghanistan", code: "af" },
    { name: "Afrique du Sud", code: "za" },
    { name: "Albanie", code: "al" },
    { name: "Algérie", code: "dz" },
    { name: "Allemagne", code: "de" },
    { name: "Andorre", code: "ad" },
    { name: "Angola", code: "ao" },
    { name: "Antigua-et-Barbuda", code: "ag" },
    { name: "Arabie Saoudite", code: "sa" },
    { name: "Argentine", code: "ar" },
    { name: "Arménie", code: "am" },
    { name: "Australie", code: "au" },
    { name: "Autriche", code: "at" },
    { name: "Azerbaïdjan", code: "az" },
    { name: "Bahamas", code: "bs" },
    { name: "Bahreïn", code: "bh" },
    { name: "Bangladesh", code: "bd" },
    { name: "Barbade", code: "bb" },
    { name: "Bélarus", code: "by" },
    { name: "Belgique", code: "be" },
    { name: "Belize", code: "bz" },
    { name: "Bénin", code: "bj" },
    { name: "Bhoutan", code: "bt" },
    { name: "Bolivie", code: "bo" },
    { name: "Bosnie-Herzégovine", code: "ba" },
    { name: "Botswana", code: "bw" },
    { name: "Brésil", code: "br" },
    { name: "Brunei", code: "bn" },
    { name: "Bulgarie", code: "bg" },
    { name: "Burkina Faso", code: "bf" },
    { name: "Burundi", code: "bi" },
    { name: "Cambodge", code: "kh" },
    { name: "Cameroun", code: "cm" },
    { name: "Canada", code: "ca" },
    { name: "Cap-Vert", code: "cv" },
    { name: "Chili", code: "cl" },
    { name: "Chine", code: "cn" },
    { name: "Chypre", code: "cy" },
    { name: "Colombie", code: "co" },
    { name: "Comores", code: "km" },
    { name: "Congo", code: "cg" },
    { name: "Corée du Nord", code: "kp" },
    { name: "Corée du Sud", code: "kr" },
    { name: "Costa Rica", code: "cr" },
    { name: "Côte d'Ivoire", code: "ci" },
    { name: "Croatie", code: "hr" },
    { name: "Cuba", code: "cu" },
    { name: "Danemark", code: "dk" },
    { name: "Djibouti", code: "dj" },
    { name: "Dominique", code: "dm" },
    { name: "Égypte", code: "eg" },
    { name: "El Salvador", code: "sv" },
    { name: "Émirats arabes unis", code: "ae" },
    { name: "Équateur", code: "ec" },
    { name: "Érythrée", code: "er" },
    { name: "Espagne", code: "es" },
    { name: "Estonie", code: "ee" },
    { name: "Eswatini", code: "sz" },
    { name: "États-Unis", code: "us" },
    { name: "Éthiopie", code: "et" },
    { name: "Fidji", code: "fj" },
    { name: "Finlande", code: "fi" },
    { name: "France", code: "fr" },
    { name: "Gabon", code: "ga" },
    { name: "Gambie", code: "gm" },
    { name: "Géorgie", code: "ge" },
    { name: "Ghana", code: "gh" },
    { name: "Grèce", code: "gr" },
    { name: "Grenade", code: "gd" },
    { name: "Guatemala", code: "gt" },
    { name: "Guinée", code: "gn" },
    { name: "Guinée-Bissau", code: "gw" },
    { name: "Guinée équatoriale", code: "gq" },
    { name: "Guyana", code: "gy" },
    { name: "Haïti", code: "ht" },
    { name: "Honduras", code: "hn" },
    { name: "Hongrie", code: "hu" },
    { name: "Îles Cook", code: "ck" },
    { name: "Îles Marshall", code: "mh" },
    { name: "Îles Salomon", code: "sb" },
    { name: "Inde", code: "in" },
    { name: "Indonésie", code: "id" },
    { name: "Irak", code: "iq" },
    { name: "Iran", code: "ir" },
    { name: "Irlande", code: "ie" },
    { name: "Islande", code: "is" },
    { name: "Israël", code: "il" },
    { name: "Italie", code: "it" },
    { name: "Jamaïque", code: "jm" },
    { name: "Japon", code: "jp" },
    { name: "Jordanie", code: "jo" },
    { name: "Kazakhstan", code: "kz" },
    { name: "Kenya", code: "ke" },
    { name: "Kirghizistan", code: "kg" },
    { name: "Kiribati", code: "ki" },
    { name: "Kosovo", code: "xk" },
    { name: "Koweït", code: "kw" },
    { name: "Laos", code: "la" },
    { name: "Lesotho", code: "ls" },
    { name: "Lettonie", code: "lv" },
    { name: "Liban", code: "lb" },
    { name: "Liberia", code: "lr" },
    { name: "Libye", code: "ly" },
    { name: "Liechtenstein", code: "li" },
    { name: "Lituanie", code: "lt" },
    { name: "Luxembourg", code: "lu" },
    { name: "Macédoine du Nord", code: "mk" },
    { name: "Madagascar", code: "mg" },
    { name: "Malaisie", code: "my" },
    { name: "Malawi", code: "mw" },
    { name: "Maldives", code: "mv" },
    { name: "Mali", code: "ml" },
    { name: "Malte", code: "mt" },
    { name: "Maroc", code: "ma" },
    { name: "Mauritanie", code: "mr" },
    { name: "Maurice", code: "mu" },
    { name: "Mexique", code: "mx" },
    { name: "Micronésie", code: "fm" },
    { name: "Moldova", code: "md" },
    { name: "Monaco", code: "mc" },
    { name: "Mongolie", code: "mn" },
    { name: "Monténégro", code: "me" },
    { name: "Mozambique", code: "mz" },
    { name: "Namibie", code: "na" },
    { name: "Nauru", code: "nr" },
    { name: "Népal", code: "np" },
    { name: "Nicaragua", code: "ni" },
    { name: "Niger", code: "ne" },
    { name: "Nigéria", code: "ng" },
    { name: "Norvège", code: "no" },
    { name: "Nouvelle-Zélande", code: "nz" },
    { name: "Oman", code: "om" },
    { name: "Ouganda", code: "ug" },
    { name: "Ouzbékistan", code: "uz" },
    { name: "Pakistan", code: "pk" },
    { name: "Palaos", code: "pw" },
    { name: "Palestine", code: "ps" },
    { name: "Panama", code: "pa" },
    { name: "Papouasie-Nouvelle-Guinée", code: "pg" },
    { name: "Paraguay", code: "py" },
    { name: "Pays-Bas", code: "nl" },
    { name: "Pays de Galles", code: "gb-wls" },
    { name: "Pérou", code: "pe" },
    { name: "Philippines", code: "ph" },
    { name: "Pologne", code: "pl" },
    { name: "Portugal", code: "pt" },
    { name: "Qatar", code: "qa" },
    { name: "République centrafricaine", code: "cf" },
    { name: "République démocratique du Congo", code: "cd" },
    { name: "République dominicaine", code: "do" },
    { name: "République tchèque", code: "cz" },
    { name: "Roumanie", code: "ro" },
    { name: "Royaume-Uni", code: "gb" },
    { name: "Russie", code: "ru" },
    { name: "Rwanda", code: "rw" },
    { name: "Saint-Kitts-et-Nevis", code: "kn" },
    { name: "Saint-Lucie", code: "lc" },
    { name: "Saint-Marin", code: "sm" },
    { name: "Saint-Vincent-et-les-Grenadines", code: "vc" },
    { name: "Samoa", code: "ws" },
    { name: "Sao Tomé-et-Principe", code: "st" },
    { name: "Sénégal", code: "sn" },
    { name: "Serbie", code: "rs" },
    { name: "Seychelles", code: "sc" },
    { name: "Sierra Leone", code: "sl" },
    { name: "Singapour", code: "sg" },
    { name: "Slovaquie", code: "sk" },
    { name: "Slovénie", code: "si" },
    { name: "Somalie", code: "so" },
    { name: "Soudan", code: "sd" },
    { name: "Soudan du Sud", code: "ss" },
    { name: "Sri Lanka", code: "lk" },
    { name: "Suède", code: "se" },
    { name: "Suisse", code: "ch" },
    { name: "Suriname", code: "sr" },
    { name: "Syrie", code: "sy" },
    { name: "Tadjikistan", code: "tj" },
    { name: "Tanzanie", code: "tz" },
    { name: "Tchad", code: "td" },
    { name: "Thaïlande", code: "th" },
    { name: "Timor-Leste", code: "tl" },
    { name: "Togo", code: "tg" },
    { name: "Tonga", code: "to" },
    { name: "Trinité-et-Tobago", code: "tt" },
    { name: "Tunisie", code: "tn" },
    { name: "Turkménistan", code: "tm" },
    { name: "Turquie", code: "tr" },
    { name: "Tuvalu", code: "tv" },
    { name: "Ukraine", code: "ua" },
    { name: "Uruguay", code: "uy" },
    { name: "Vanuatu", code: "vu" },
    { name: "Vatican", code: "va" },
    { name: "Venezuela", code: "ve" },
    { name: "Viêt Nam", code: "vn" },
    { name: "Yémen", code: "ye" },
    { name: "Zambie", code: "zm" },
    { name: "Zimbabwe", code: "zw" },
    // Nations rugby (home nations UK)
    { name: "Angleterre", code: "gb-eng" },
    { name: "Écosse", code: "gb-sct" },
    { name: "Irlande du Nord", code: "gb-nir" },
];

// Triée alphabétiquement
COUNTRIES.sort((a, b) => a.name.localeCompare(b.name, "fr"));

/** URL d'un drapeau 16x12 via flagcdn.com */
export function getFlagUrl(code: string): string {
    return `https://flagcdn.com/16x12/${code.toLowerCase()}.png`;
}

export function getCountryByCode(code: string): Country | undefined {
    return COUNTRIES.find((c) => c.code === code.toLowerCase());
}
