import { type RouteConfig, index, route } from "@react-router/dev/routes";

export default [
    index("routes/home.tsx"),
    route(".well-known/appspecific/com.chrome.devtools.json", "routes/well-known-devtools.tsx"),
    route("tracker", "routes/tracker.tsx"),
    route("roster", "routes/roster.tsx"),
    route("r/:rosterId/p/:playerId", "routes/player-profile.tsx"),
    route("r/:rosterId/team", "routes/roster-profile.tsx"),
    route("r/:rosterId/coach", "routes/coach-profile.tsx"),
    route("r/:rosterId/president", "routes/president-profile.tsx"),
    route("r/:rosterId", "routes/roster-detail.tsx"),
    route("syntheses", "routes/syntheses.tsx"),
    route("syntheses/:summaryId", "routes/synthese-detail.tsx"),
    route("account", "routes/settings.tsx"),
    route("admin", "routes/admin.tsx"),
    route("admin/accounts", "routes/admin-accounts.tsx"),
    route("live/:publicSlug", "routes/live-view.tsx"),
    route("live/:publicSlug/roster", "routes/live-roster.tsx"),
    route("admin/db", "routes/admin-db.tsx"),
    route("api/account", "routes/api/account.ts"),
    route("api/admin/accounts", "routes/api/admin-accounts.ts"),
    route("api/rosters", "routes/api/rosters.ts"),
    route("api/summaries", "routes/api/summaries.ts"),
    route("api/match-day-teams", "routes/api/match-day-teams.ts"),
    route("api/live-matches", "routes/api/live-matches.ts"),
    route("api/live-matches/:matchId", "routes/api/live-match-update.ts"),
    route("api/live-matches/:matchId/close", "routes/api/live-match-close.ts"),
    route("api/live/:publicSlug/state", "routes/api/live-public-state.ts"),
    route("api/live/:publicSlug/stream", "routes/api/live-stream.ts"),

    // CRUD API routes
    route("api/players", "routes/api/players.ts"),
    route("api/coaches", "routes/api/coaches.ts"),
    route("api/presidents", "routes/api/presidents.ts"),
    route("api/competitions", "routes/api/competitions.ts"),
    route("api/titles", "routes/api/titles.ts"),
    route("api/search", "routes/api/search.ts"),
    route("api/calendar-sync", "routes/api/calendar-sync.ts"),
] satisfies RouteConfig;
